### PR TITLE
Add Column decorations (first hollowed lines and alternate length)

### PR DESCRIPTION
**Pull request by sigmundfred**
The goal of this request is to add options to the column creation.

### CODE REVIEW

**Comment by ranjian0** [comment]
Sorry for taking my sweet time jumping on this. Currently reviewing

**Comment by ranjian0** [comment]
I am getting this error. 

image

Maybe `create_plane` is a new function you made and didn't commit.

**Comment by sigmundfred** [comment]
Yes you are right

**Comment by ranjian0** [comment]
Looks like decoration columns only apply to the first floor. Is this intended behaviour? Seems off.

image

**Comment by sigmundfred** [comment]
Issue fixed

**Pull request merged**
